my_flask_app/funnels/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length




class FunnelForm(FlaskForm):
    """Funnel Create Form"""

my_flask_app/funnels/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

my_flask_app/funnels/views.py
from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
    json
)
from flask_login import login_required, login_user, logout_user

from my_flask_app.extensions import login_manager
from my_flask_app.funnels.forms import FunnelForm
from my_flask_app.utils import flash_errors
from my_flask_app.funnels.view_commands import get_funnel_data, create_funnel, get_funnel_stats
from my_flask_app.user.models import Funnel, Cost
from my_flask_app.funnels.funnel_table import get_funnel_table, get_csv

blueprint = Blueprint("funnels", __name__, url_prefix="/funnel",static_folder="../static")

@blueprint.route("/create", methods=['POST','GET'])
@login_required
def funnel_creator():

    if request.method == 'POST':
        f = request.form
        data = {}
        for key in f.keys():
            for value in f.getlist(key):
                data[key] = value
        print(data)
        create_funnel(data)
        return ('success', 200)
    else:
        form = FunnelForm(request.form)

        return render_template("public/funnelform.html", form = form)

#Serves Edit Form and also sends data to Frontend to fill out form on load
@blueprint.route("/editor/<id>", methods=['POST','GET'])
@login_required
def edit_funnel(id):
    """About page."""
    if request.method == 'POST':
        d = get_funnel_data(id)
        return d
    else:
        form = FunnelForm(request.form)
        return render_template("public/editForm.html", form = form)

# Post Function for the Funnel Editor Form View : Updates Existing Funnel
@blueprint.route("/update/<id>", methods=['POST'])
def update_funnel(id):
    """About page."""
    if request.method == 'POST':
        d = get_funnel_data(id)
        return d
    

@blueprint.route("/stats/<id>", methods=['GET'])
def funnel_data(id):
    """ Retrieve Funnel Data"""
    json_rslt = get_funnel_stats(id)
    return render_template("public/funnelStats.html", data = json_rslt)

@blueprint.route("/stats/recalc/<id>", methods=['GET'])
def recalc_stats(id):
    """ Retrieve Funnel Data"""
    json_rslt = get_funnel_stats(id)
    return (json_rslt, 200)

@blueprint.route("/stats/table", methods=['GET'])
def build_table():
    """ Retrieve Funnel Data"""
    json_rslt = get_funnel_table()
    return (json_rslt, 200)
@blueprint.route("/stats/export/<funnel_id>", methods=['GET'])
def export_csv(funnel_id):
    """ Retrieve Funnel Data"""
    return (get_csv(funnel_id), 200)

my_flask_app/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    """List members."""
    return render_template("users/members.html")

my_flask_app/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.login')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

my_flask_app/templates/base.html
<!doctype html>
<html class="no-js" lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
    {% if data: %}
    
      {% block page_title %} {{data['name']}} | Funnel Stats | JKW Enterprises{% endblock %}
    {% else %}
       Home | JKW Enterprises
    {% endif %}
  </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="{% block meta_author %}Sebastian Ruml{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="{{static_url_for('static', filename='build/img/favicon.ico') }}">
    <!-- Place favicon.ico in the root directory -->

    <link
    rel="stylesheet"
    type="text/css"
    href="{{ static_url_for('static', filename='build/main_css.bundle.css') }}"
  />

    {% block css %}{% endblock %}

    <!-- <script src="js/vendor/modernizr-2.8.3.min.js"></script> -->
  </head>

  <body id="page-top">
    <div id="wrapper">
      
    {% include "includes/navbar.html" %}
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">
        {% include "includes/topbar.html" %}
      {% block content %}{% endblock %}


    
    

    <!-- Custom Javascript -->
    <!-- JavaScript at the bottom for fast page loading -->
    {% block js %}{% endblock %}
    <script src="{{ static_url_for('static', filename='build/main_js.bundle.js') }}"></script>
    

    <!-- Google Analytics -->
    </div>
    {% include "includes/footer.html" %}
      </div>
      <!-- End Content Wrapper -->
</div>
  </body>

</html>

my_flask_app/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© connor hatcher</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:cbh4ou@gmail.com,">Contact</a></li>
    </ul>
  </small>
</footer>

my_flask_app/templates/funnelForms.html
<!doctype html>
<html class="no-js" lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
 {% block page_title %} Funnel Editor | JKW Enterprises{% endblock %}
   </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="{% block meta_author %}Sebastian Ruml{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="{{static_url_for('static', filename='build/img/favicon.ico') }}">
    <!-- Place favicon.ico in the root directory -->

    <link
    rel="stylesheet"
    type="text/css"
    href="{{ static_url_for('static', filename='build/main_css.bundle.css') }}"
  />

    {% block css %}{% endblock %}

    <!-- <script src="js/vendor/modernizr-2.8.3.min.js"></script> -->
  </head>

  <body id="page-top">
    <div id="wrapper">
      
    {% include "includes/navbar.html" %}
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">
        {% include "includes/topbar.html" %}
      {% block content %}{% endblock %}


    
    

    <!-- Custom Javascript -->
    <!-- JavaScript at the bottom for fast page loading -->
    {% block js %}{% endblock %}
    <script src="{{ static_url_for('static', filename='build/funnel_js.bundle.js') }}"></script>
    

    <!-- Google Analytics -->
    </div>
    {% include "includes/footer.html" %}
      </div>
      <!-- End Content Wrapper -->
</div>
  </body>

</html>

my_flask_app/templates/layout.html
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
  <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <link rel="shortcut icon" href="{{static_url_for('static', filename='build/img/favicon.ico') }}">
    <title>
      {% block page_title %} 
      Funnel Calculator
       {% endblock %}
    </title>
    <meta
      name="description"
      content="{% block meta_description %}{% endblock %}"
    />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ static_url_for('static', filename='build/main_css.bundle.css') }}"
    />

    {% block css %}{% endblock %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %} {% with form=form %} {% include "nav.html" %} {% endwith %}

    <header>{% block header %}{% endblock %}</header>

    <main role="main">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert"
              >&times;</a
            >
            {{ message }}
          </div>
          <!-- end .alert -->
          {% endfor %}
        </div>
        <!-- end col-md -->
      </div>
      <!-- end row -->
      {% endif %} {% endwith %} {% block content %}{% endblock %}
    </main>

    {% include "footer.html" %}

    <!-- JavaScript at the bottom for fast page loading -->
    <script src="{{ static_url_for('static', filename='build/main_js.bundle.js') }}"></script>
    {% block js %}{% endblock %}
    <!-- end scripts -->
    {% endblock %}
  </body>
</html>

my_flask_app/templates/loginBase.html
<!doctype html>
<html class="no-js" lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
      {% block page_title %} Login | JKW Enterprises{% endblock %}
    </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="{% block meta_author %}Connor Hatcher{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="{{static_url_for('static', filename='build/img/favicon.ico') }}">
    <!-- Place favicon.ico in the root directory -->

    <link
    rel="stylesheet"
    type="text/css"
    href="{{ static_url_for('static', filename='build/main_css.bundle.css') }}"
  />

    {% block css %}{% endblock %}

    <!-- <script src="js/vendor/modernizr-2.8.3.min.js"></script> -->
  </head>

  <body class="bg-gradient-primary">
    
        
      {% block content %}{% endblock %}


    
    

    <!-- Custom Javascript -->
    <!-- JavaScript at the bottom for fast page loading -->
    <script src="{{ static_url_for('static', filename='build/main_js.bundle.js') }}"></script>
    {% block js %}{% endblock %}

    <!-- Google Analytics -->
    </div>
      </div>
      <!-- End Content Wrapper -->
</div>
  </body>

</html>

my_flask_app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{{ url_for('public.home') }}">
     My Flask App 
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('public.home') }}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.about') }}">About</a>
      </li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="navbar-nav my-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.logout') }}">
          <i class="fa fa-sign-out"></i>
        </a>
      </li>
    </ul>
    {% elif form %}
    <form class="form-inline" id="loginForm" method="POST" action="/" role="login">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <div class="input-group mb-2 mr-sm-2">
        {{ form.username(placeholder="Username", class_="form-control mr-sm-1 my-auto") }} {{ form.password(placeholder="Password",
        class_="form-control mr-sm-1 my-auto") }}
        <button class="btn btn-light btn-primary m-auto" type="submit">Login</button>
      </div>
    </form>
    <ul class="navbar-nav my-auto">
      <li class="nav-item">
        <a class="nav-link navbar-text" href="{{ url_for('public.register') }}">Create account</a>
      </li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
</nav>

my_flask_app/templates/stats.html
<!doctype html>
<html class="no-js" lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
 {% block page_title %} Funnel Stats | JKW Enterprises{% endblock %}
   </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="{% block meta_author %}Sebastian Ruml{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="{{static_url_for('static', filename='build/img/favicon.ico') }}">
    <!-- Place favicon.ico in the root directory -->

    <link
    rel="stylesheet"
    type="text/css"
    href="{{ static_url_for('static', filename='build/main_css.bundle.css') }}"
  />

    {% block css %}{% endblock %}

    <!-- <script src="js/vendor/modernizr-2.8.3.min.js"></script> -->
  </head>

  <body id="page-top">
    <div id="wrapper">
      
    {% include "includes/navbar.html" %}
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">
        {% include "includes/topbar.html" %}
      {% block content %}{% endblock %}


    
    

    <!-- Custom Javascript -->
    <!-- JavaScript at the bottom for fast page loading -->
    {% block js %}{% endblock %}
    <script src="{{ static_url_for('static', filename='build/stats_js.bundle.js') }}"></script>
    

    <!-- Google Analytics -->
    </div>
    {% include "includes/footer.html" %}
      </div>
      <!-- End Content Wrapper -->
</div>
  </body>

</html>